### ISSUE TITLE
Organise Michael's Feedback

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#32]
Client interface:
* Need better visible feedback when they log in (other than just “no current polls”)
* When viewing a poll, ideally it should say the unit (collection), maybe instead of “MARS” in the title bar.
* Students should be able to see a list of the streams they have joined (somewhere… from a menu)
* Why does it use the terminology “feed” and not “unit”, is this a conscious choice?  You also have stream and collection which refer to the same thing from different sides, I think. Not sure of consistency.

Admin interface:
* Lock and unlock icons are not particularly obvious.  Could you have a Play/ pause button, and reset button.
* Also at some point I’m pretty certain the top bar was showing the lock icon while it was locked and the unlock icon while it was locked.  Later it worked fine.
* Stream code to join the collection should be displayed when managing the collection, i.e., when adding groups (without having to open a poll and run it to find out).  I needed to create, open and run several polls to convince myself that the code was per unit rather than per poll (since it was displayed in the admin interface for the poll).
* Is the number ‘total’ number the number of respondents or the number of responses.  It seems to be the later, but then showing values out of total doesn’t add up once people have changed responses.
* I would like to have the bars show text percentages of the total respondents.  I’d like to be able to talk about in terms of percentages, and I’m not that great at computing them!  If each bar showed count and percentage, and total was only shown in one place at the top this would use about the same amount of space (since total is shown on every bar)
* The placement of controls in the interface for creating and managing collections, groups and polls could be improved.
* Restarting of a poll is only remembered if you then unlock the poll before doing anything else.  I restarted all the polls and was then confused when I went back into them and they were showing the last results and were no longer reset.  (I think this was the same device)

**Comment by aj1331** [comment]
Client interface:
* Need better visible feedback when they log in (other than just “no current polls”) [Issue 33](https://github.com/SLC3/MARS/issues/33)
* When viewing a poll, ideally it should say the unit (collection), maybe instead of “MARS” in the title bar. [Issue 30](https://github.com/SLC3/MARS/issues/30)
* Students should be able to see a list of the streams they have joined (somewhere… from a menu) [Issue 34](https://github.com/SLC3/MARS/issues/34)
* Why does it use the terminology “feed” and not “unit”, is this a conscious choice?  You also have stream and collection which refer to the same thing from different sides, I think. Not sure of consistency. [Issue 36](https://github.com/SLC3/MARS/issues/36)

Admin interface:
* Lock and unlock icons are not particularly obvious.  Could you have a Play/ pause button, and reset button. [Issue 35](https://github.com/SLC3/MARS/issues/35)
* Also at some point I’m pretty certain the top bar was showing the lock icon while it was locked and the unlock icon while it was locked.  Later it worked fine. [Issue 37](https://github.com/SLC3/MARS/issues/37)
* Stream code to join the collection should be displayed when managing the collection, i.e., when adding groups (without having to open a poll and run it to find out).  I needed to create, open and run several polls to convince myself that the code was per unit rather than per poll (since it was displayed in the admin interface for the poll). [Issue 38](https://github.com/SLC3/MARS/issues/38)
* Is the number ‘total’ number the number of respondents or the number of responses.  It seems to be the later, but then showing values out of total doesn’t add up once people have changed responses. [Issue 39](https://github.com/SLC3/MARS/issues/39)
* I would like to have the bars show text percentages of the total respondents.  I’d like to be able to talk about in terms of percentages, and I’m not that great at computing them!  If each bar showed count and percentage, and total was only shown in one place at the top this would use about the same amount of space (since total is shown on every bar) [Issue 31](https://github.com/SLC3/MARS/issues/31)
* The placement of controls in the interface for creating and managing collections, groups and polls could be improved. [Issue 40](https://github.com/SLC3/MARS/issues/40)
* Restarting of a poll is only remembered if you then unlock the poll before doing anything else.  I restarted all the polls and was then confused when I went back into them and they were showing the last results and were no longer reset.  (I think this was the same device) [Issue 41](https://github.com/SLC3/MARS/issues/41)
