### ISSUE TITLE
Make a copy to clipboard button in the poll creator view

### ISSUE THREAD

**Issue by nathansherburn** [SLC3/MARS#52]
At the moment, lecturers need to write a poll up in ppt and then copy and paste every question and answer individually into MARS - this will no do!

I propose a copy & paste button in the poll maker that'll allow lecturers to:
1. create the poll in the poll maker
2. click the copy to clipboard button
3. paste their poll into ms ppt/google slides/keynote whatever

Thoughts?

**Comment by aj1331** [comment]
Not sure whether lecturers actually need to copy/paste polls into a ppt. They can activate a poll without unlocking it if they want to show it without people being able to answer. 

Anyway copying needs to be something plugins can opt to support, rather than hard-coded for specific plugin types. See the changes in 9ea29a5ae4f8cfa33c425ccf10c0a7e1638de065

**Comment by nathansherburn** [comment]
At the moment, displaying an unlocked poll through MARS has a few issues:
1. We use ellipsis for overflowing answers (this maintains the formatting nicely but it could be changed to a wordwrap)
2. Lecturers will often need to show an image like a circuit along with the question.

We could look into making poll is activated screen more "display question" friendly and make displaying or not displaying live results an option on the polls.

**Comment by thanatos6666** [comment]
The majority of use cases with academics will be in conjunction with PowerPoint, where PowerPoint will display the question and any images. 

If there is a use case for a copy-to-clipboard function, it will be to copy multichoice polls answers and pasting them formatted as a standard bullet-list.
