### ISSUE TITLE
Force refresh of browser when new version is detected?

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#57]
When a new version of MARS is released, the client should automatically refresh itself to the latest version.

e.g. on release of 0.4.0, when visiting mars.mu, I did not receive new features until I refreshed the site.

**Comment by nathansherburn** [comment]
Should be taken care of now.

I added `add_header Cache-Control "no-cache";` to nginx's config based on what I've read here:
* https://www.mnot.net/cache_docs/#CACHE-CONTROL
* http://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache

We won't need to touch the node side because express will always deliver the latest data but we'll need to restart nginx before these changes go through.

**Comment by aj1331** [comment]
I don't think this is the right approach. It's app.min.css and app.min.js that are being cached (which is what we want) and we want them to refresh only on new versions. From the links on the stack overflow answer "no-cache" behaviour isn't consistent across browsers and it can cause them to not cache the files. The common way to solve this seems to be appending the version number (or some changing token) as a query string to the urls in link and script tags (eg. 'app.min.js?v=0.4.0'). 

I'll add a step to the gulp 'build' task to sub in the version number, read from package.json. When an update is ready to be applied to the server it's a release and should have a version number bump. After updates are applied you should always run `npm install` which is now running `gulp build` as a post-install command (0613ff336e31b95554ed0abca14e4deea1c27677), so there's no extra work involved in updating.

**Comment by nathansherburn** [comment]
Sounds good!
