### ISSUE TITLE
Leaderboard needs a "refresh" button

### ISSUE THREAD

**Issue by thanatos6666** [SLC3/MARS#68]
Leaderboard does not refresh properly when students that have not answered a question answer a question.

Upon entering the leaderboard interface, it appears to refresh (and probably does it correctly) for those students that have answered a question previously.

To get students that have recently answered to display, this requires the Lecturer to click "Update" and "Update". This should be a one step process with a "Refresh" icon next to the "Update" as shown:

![image](https://cloud.githubusercontent.com/assets/4758245/15277470/d0e02358-1b48-11e6-9479-5146aa13c198.png)

The term "Update" is confusing, should be changed to something like "Select questions"

**Comment by thanatos6666** [comment]
Actually, the "Refresh" and "Update" icons should be moved to the top of the card.

**Comment by aj1331** [comment]
It doesn't "Refresh" on loading, it renders the saved leaderboard data from
the database. Generating ("Updating") this data can take a couple of
seconds for polls that have a lot of responses, which is why it's not
generated on the fly. It has to get every result for each of the polls
selected, then merge them together, filter out incorrect responses and
assign scores (which is all done in the client because the sever has no
concept of "multiple-choice"). The result of this is saved to the database.

I can add a "Refresh" button but it still has to go through this process.
It will really be an "Update with the last used selection of polls" button.
Is that okay?

**Comment by thanatos6666** [comment]
Yes, that's fine, right now, it's a 2 step process (Click "Update", then click "Update" again).

You can even keep the name as "Update" for the 1-step button, and change the current "Update" procedure to "Select Questions for Leaderboard" or something like that.
